version: "2"
services:
    sqlite:
        image: webdevnicolasfourcade/sqlite3:latest
        container_name: sqlite-db
        environment:
            SQLITE_ROOT_PASSWORD: password
        stdin_open: true
        tty: true
        volumes:
            - ./sqlite-db/:/root/db/
    site:
        image: webdevnicolasfourcade/ubuntu-php7.1:latest
        container_name: web
        ports:
            - "8080:80"
        expose:
            - "80"
        depends_on:
            - sqlite
        volumes:
          - ./chooseit-basket:/app